# Generated by Django 3.1.4 on 2020-12-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20201216_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
    ]
