# Generated by Django 3.1.2 on 2020-12-22 16:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_remove_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlistname',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=None),
        ),
    ]
