# Generated by Django 3.1.2 on 2020-12-22 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20201222_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None),
        ),
    ]
