# Generated by Django 3.1.2 on 2020-12-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_auto_20201222_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songlist',
        ),
    ]
