# Generated by Django 3.1.4 on 2020-12-22 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_remove_playlist_songlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=[], size=None),
        ),
    ]
